-- MySQL Script generated by MySQL Workbench
-- Wed Nov 11 14:12:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `DNI` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Fecha nacimiento` VARCHAR(45) NULL,
  `Dni_cabeza` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Area` VARCHAR(45) NULL,
  `Concejal` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bloque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bloque` (
  `Calle` VARCHAR(45) NOT NULL,
  `Nº` INT NOT NULL,
  `Cantidad de personas` INT NULL,
  `Nombre_Zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Calle`, `Nº`),
  INDEX `NombreZona_idx` (`Nombre_Zona` ASC) VISIBLE,
  CONSTRAINT `NombreZona`
    FOREIGN KEY (`Nombre_Zona`)
    REFERENCES `mydb`.`Zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Piso` (
  `Calle` VARCHAR(45) NOT NULL,
  `Nº` INT NOT NULL,
  `Planta` INT NOT NULL,
  `Letra` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`Calle`, `Nº`, `Planta`, `Letra`),
  CONSTRAINT `Calle`
    FOREIGN KEY (`Calle` , `Nº`)
    REFERENCES `mydb`.`Bloque` (`Calle` , `Nº`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vivienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivienda` (
  `Calle` VARCHAR(45) NOT NULL,
  `Nº` INT NOT NULL,
  `Cantidad de personas` INT NULL,
  PRIMARY KEY (`Calle`, `Nº`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
